plugins {
    id 'java-library'
}

group = 'outing'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

def libs = extensions.getByType(VersionCatalogsExtension).named('libs')

dependencies {
    implementation platform(libs.findLibrary('spring-boot-bom').get())
    annotationProcessor platform(libs.findLibrary('spring-boot-bom').get())
    testImplementation platform(libs.findLibrary('spring-boot-bom').get())
    testAnnotationProcessor platform(libs.findLibrary('spring-boot-bom').get())

    compileOnly libs.findLibrary('lombok').get()
    annotationProcessor libs.findLibrary('lombok').get()
    testCompileOnly libs.findLibrary('lombok').get()
    testAnnotationProcessor libs.findLibrary('lombok').get()

    testImplementation libs.findLibrary('starter-test').get()
    testRuntimeOnly libs.findLibrary('junit-launcher').get()
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
