services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-server-1
      - backend-server-2

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    expose:
      - "3306"

  backend-server-1:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      SERVER_NAME: backend-server-1
      DB_HOST: 
      DB_PORT: 
      DB_NAME: 
      DB_USERNAME: 
      DB_PASSWORD: 
    entrypoint: ["sh", "-c", "sleep 10 && exec java -jar /app/app.jar"]
    expose:
      - "8080"
    
  backend-server-2:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      SERVER_NAME: backend-server-2
      DB_HOST: 
      DB_PORT: 
      DB_NAME: 
      DB_USERNAME: 
      DB_PASSWORD: 
    entrypoint: ["sh", "-c", "sleep 10 && exec java -jar /app/app.jar"]
    expose:
      - "8080"
