plugins {
    alias(libs.plugins.dependency.analysis)
}

subprojects {
    apply plugin: 'java'
    apply plugin: libs.plugins.dependency.analysis.get().pluginId

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation platform(libs.spring.boot.bom)
 
        testImplementation libs.starter.test
        testRuntimeOnly libs.junit.launcher
    }

    test {
        useJUnitPlatform()
    }
}